version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - workflow-net
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./output_docs:/app/output_docs
      - ./:/app/
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - PYTHONPATH=/app
    command: >
      sh -c "chmod +x /app/docker/entrypoint.sh &&
             pip install -r docker/requirements.txt &&
             uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug"
    networks:
      - workflow-net
    healthcheck:
      disable: true

networks:
  workflow-net:
    driver: bridge 