version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - ./docker/entrypoint.sh:/app/docker/entrypoint.sh
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: ["/app/docker/entrypoint.sh", "frontend"]
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    volumes:
      - .:/app
      - ./docker/entrypoint.sh:/app/docker/entrypoint.sh
      - /app/output_docs
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: ["/app/docker/entrypoint.sh", "api"]

networks:
  default:
    name: workflow-net 